version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: billing-postgres
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: qwerty123
    ports:
       - "5433:5432"
    volumes:
       - billing_pgdata_v2:/var/lib/postgresql/data

volumes:
  billing_pgdata_v2:
    name: billing_pgdata_v2